services:
  mariadb:
    ports: [] # Don't expose port to host machine. Services in Dockerfile can still access MariaDB though

  elasticsearch:
    ports: [] # See MariaDB ports comment

  api:
    ports:
      - "3041:8000"
    volumes:
      - ml_models:/app/ml_models # Shared volume for ML models
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers
    networks:
      - default
      - nginx-proxy

  frontend:
    ports:
      - "3040:3000"
    build:
      target: production
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL} # Expose env var to frontend during build time so NEXT_PUBLIC_API_URL is available
    command: npm run start
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy # Used for reverse proxy across multiple services
    external: true

volumes:
  ml_models: # Shared volume for ML models
